import React from "react";
import { Link } from "react-router-dom";
import SectionHeader from "../components/SectionHeader";
import { getPrograms } from "../api/programs.api";
import { getProjects } from "../api/projects.api";
import { getNews } from "../api/news.api";
import { getEvents } from "../api/events.api";
import { getGallery } from "../api/gallery.api";
export function ProgramsPage(){const [d,setD]=React.useState([]);React.useEffect(()=>{getPrograms().then(setD).catch(()=>{})},[]);return <ListShell title="Our Programs" text="Explore the areas where DDA works with communities." kicker="WHAT WE DO"><div className="public-grid">{d.map(x=><article className="public-card" key={x.id}><h3>{x.title}</h3><p>{x.shortDescription}</p><Link to={`/programs/${x.slug}`}>Explore program →</Link></article>)}</div></ListShell>}
export function ProjectsPage(){const [d,setD]=React.useState([]);React.useEffect(()=>{getProjects().then(setD).catch(()=>{})},[]);return <ListShell title="Our Projects" text="Discover DDA initiatives and community-led work." kicker="OUR WORK"><div className="public-grid">{d.map(x=><article className="public-card" key={x.id}>{x.imageUrl&&<img src={x.imageUrl} alt={x.title}/>}<small>{x.program?.title||x.status}</small><h3>{x.title}</h3><p>{x.shortDescription}</p><Link to={`/projects/${x.slug}`}>View project →</Link></article>)}</div></ListShell>}
export function NewsPage(){const [d,setD]=React.useState([]);React.useEffect(()=>{getNews().then(setD).catch(()=>{})},[]);return <ListShell title="News & Stories" text="Updates from DDA's community development work." kicker="LATEST FROM DDA" crossLink={{to:"/events",label:"See upcoming events"}}><div className="public-grid">{d.map(x=><article className="public-card" key={x.id}>{x.imageUrl&&<img src={x.imageUrl} alt={x.title}/>}<small>{x.publishedAt?new Date(x.publishedAt).toLocaleDateString():"Published"}</small><h3>{x.title}</h3><p>{x.excerpt}</p><Link to={`/news/${x.slug}`}>Read story →</Link></article>)}</div></ListShell>}
export function EventsPage(){const [d,setD]=React.useState([]);React.useEffect(()=>{getEvents().then(setD).catch(()=>{})},[]);return <ListShell title="Events" text="Stay connected with DDA activities and community events." kicker="EVENTS" crossLink={{to:"/news",label:"Read the latest news"}}><div className="public-grid">{d.map(x=><article className="public-card" key={x.id}>{x.imageUrl&&<img src={x.imageUrl} alt={x.title}/>}<small>{new Date(x.eventDate).toLocaleString()}</small><h3>{x.title}</h3><p>{x.description}</p><span>{x.location||"Meki, Ethiopia"}</span><Link to={`/events/${x.slug}`}>View details →</Link></article>)}</div></ListShell>}
export function GalleryPage(){const [d,setD]=React.useState([]);React.useEffect(()=>{getGallery().then(setD).catch(()=>{})},[]);return <ListShell title="Community Gallery" text="Stories and moments from DDA's work." kicker="GALLERY"><div className="gallery-grid public-gallery">{d.map(x=><figure key={x.id}><img src={x.imageUrl} alt={x.title||x.caption||"DDA community"}/>{x.caption&&<figcaption>{x.caption}</figcaption>}</figure>)}</div></ListShell>}
function ListShell({kicker,title,text,children,crossLink}){return <main className="public-page"><div className="container"><SectionHeader kicker={kicker} title={title} text={text}/>{crossLink&&<p className="list-crosslink"><Link to={crossLink.to}>{crossLink.label} →</Link></p>}{children}</div></main>}
